ai:
  koog:
    agents:
      tracing: false
    chat-memory:
      session-store:
        path: "./var/tmp/session-store"
    rag:
      embedding-store:
        path: "./var/tmp/embedding-store"
      knowledge-base:
        path: "./data/knowledge"

logging:
  level:
    "ai.koog": info
    "io.micrometer.registry.otlp": error
    "org.springframework.web": info

server:
  shutdown: immediate
  http2:
    enabled: true
  servlet:
    jsp:
      registered: false
  netty:
    idle-timeout: 30s
    connection-timeout: 10s

management:
  otlp:
    metrics:
      export:
        step: 3s
spring:
  application:
    name: ${build.name}
  config:
    import:
      - "classpath:/META-INF/build-info.properties"