
ai:
    koog:
        openai:
            api-key: ${OPENAI_API_KEY}

logging:
    level:
        "org.springframework.web": debug
        "ai.koog": debug

server:
    shutdown: immediate
    http2:
        enabled: true
    servlet:
        jsp:
            registered: false


management:
    otlp:
        metrics:
            export:
                step: 3s
spring:
    application:
        name: ${build.name}
    config:
        import:
        - "classpath:/META-INF/build-info.properties"