ai:
  koog:
    agents:
      tracing: false
    chat-memory:
      session-store:
        path: "./target/tmp/session-store"
    prompt-template:
      path: "./data/prompt-templates"
    rag:
      embedding-store:
        path: "./target/tmp/embedding-store"
      knowledge-base:
        path: "./data/knowledge"

logging:
  level:
    "ai.koog": info
    "io.micrometer.registry.otlp": error
    "org.springframework.web": info

server:
  shutdown: immediate
  http2:
    enabled: true
  servlet:
    jsp:
      registered: false
  netty:
    idle-timeout: 30s
    connection-timeout: 10s


management:
  otlp:
    metrics:
      export:
        step: 3s

  endpoint:
    health:
      probes:
        enabled: true
        ## https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.kubernetes-probes
        add-additional-paths: true
spring:
  application:
    name: ${build.name}
  config:
    import:
      - "classpath:/META-INF/build-info.properties"
