# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'chat-ui/**'
      - 'promptfoo/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'chat-ui/**'
      - 'promptfoo/**'
  workflow_dispatch:

permissions:
  contents: read # access to check out code and install dependencies

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  # Cancel only when the run is NOT on `main` branch
  cancel-in-progress: ${{ github.ref != 'refs/heads/main'  }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 24
      uses: actions/setup-java@v5
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean verify

    - name: Collect reports
      if: ${{ !failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: reports-${{ matrix.os }}
        path: |
          **/target/*-reports/

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: ${{ !cancelled() }}
      with:
        report_paths: '**/target/*-reports/TEST-*.xml'
        annotate_only: true
        detailed_summary: true
        flaky_summary: true
        include_empty_in_summary: false
        skip_success_summary: true
